CC=c99

sort: sort.c selection_sort.c heap.c merge.c queue.c common.c quick.c
	$(CC) -g -Wall sort.c selection_sort.c heap.c merge.c queue.c common.c quick.c -o sort
search: search.c binsearch.c selection_sort.c heap.c merge.c queue.c common.c quick.c
	$(CC) -g -Wall search.c binsearch.c selection_sort.c heap.c merge.c queue.c common.c quick.c -o search
graph: graph.c queue.c
	$(CC) -g -Wall graph.c queue.c -o graph
